'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:4.0.30319.42000
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'このクラスは StronglyTypedResourceBuilder クラスが ResGen
    'または Visual Studio のようなツールを使用して自動生成されました。
    'メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    '''<summary>
    '''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WpfSandboxLib.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property _01_011_響_アイコン() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_01_011_響_アイコン", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property _02_021_ひめ_アイコン() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_02_021_ひめ_アイコン", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property _02_021_ひめ_冬服_ポーズ１_ジト目_150418_00s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_02_021_ひめ_冬服_ポーズ１_ジト目_150418_00s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property _02_021_ひめ_冬服_ポーズ１_喜_150418_00s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_02_021_ひめ_冬服_ポーズ１_喜_150418_00s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property _02_021_ひめ_冬服_ポーズ１_照_150418_00s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_02_021_ひめ_冬服_ポーズ１_照_150418_00s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property _02_021_ひめ_冬服_ポーズ１_通常１_150418_00s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_02_021_ひめ_冬服_ポーズ１_通常１_150418_00s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property _02_021_ひめ_冬服_ポーズ１_通常２_150418_00s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_02_021_ひめ_冬服_ポーズ１_通常２_150418_00s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property _04_031_せつな_アイコン() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_04_031_せつな_アイコン", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property _04_031_せつな立ち絵きょとんs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_04_031_せつな立ち絵きょとんs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property _04_031_せつな立ち絵微笑みs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_04_031_せつな立ち絵微笑みs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property _04_031_せつな立ち絵笑顔s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_04_031_せつな立ち絵笑顔s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property chara() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chara", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property chara_a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chara_a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property chara_k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chara_k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property chara_w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chara_w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property hibiki_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hibiki_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property hibiki_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hibiki_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property hime_iya() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hime_iya", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property hime_kanasii() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hime_kanasii", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property hime_ko() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hime_ko", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property hime_love() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hime_love", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property hime_okoru() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hime_okoru", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property hime_tanosii() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hime_tanosii", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property hime_yorokobu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hime_yorokobu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property kiri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kiri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property kiri_a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kiri_a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property kiri_k() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kiri_k", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property mail_icon_free5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_icon_free5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property mark_face_angry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mark_face_angry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property mark_face_ase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mark_face_ase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property mark_face_cry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mark_face_cry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property mark_face_hehe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mark_face_hehe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property mark_face_jito() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mark_face_jito", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property mark_face_laugh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mark_face_laugh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property mark_face_odoroki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mark_face_odoroki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property mark_face_smile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mark_face_smile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property mark_face_tere() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mark_face_tere", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property ひめミニキャラ１() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ひめミニキャラ１", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property ひめミニキャラ2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ひめミニキャラ2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property ひめミニキャラ3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ひめミニキャラ3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property ひめミニキャラ4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ひめミニキャラ4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property ひめミニキャラ5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ひめミニキャラ5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        '''</summary>
        Friend ReadOnly Property ひめミニキャラ6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ひめミニキャラ6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
